service: lambda-s3-rekognition

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, 'stage'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:*
        - s3:*
        - sns:*
        - iam:*
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "*"
  environment:
    VIDEOS_TABLE_NAME: ${self:custom.videosTableName}
  
package:
  artifact: target/lambda-s3-rekognition-1.0.jar
  
custom:
  stage: ${opt:stage}
  videosTableName: 'rekognition-videos-${self:provider.stage}'

# all lambda functions are here, trigger by s3, SNS
functions:
  check-video:
    handler: com.aws.lambda.handler.S3EventHandler
    timeout: 60
    environment:
      rekognitionSNSArn: { "Fn::Join" : ["", ["arn:aws:sns:us-east-1:", { "Ref" : "AWS::AccountId" }, ":AmazonRekognitionTopic1" ]]}
      roleArn: { "Fn::Join" : ["", ["arn:aws:iam::", { "Ref" : "AWS::AccountId" }, ":role/RekognitionLambda" ]]}
    events:
      - s3:
          bucket: 'rekognition-videos-bucket'
          event: s3:ObjectCreated:*
          rules:
            - suffix: .mp4
  fetch-rekognition:
    handler: com.aws.lambda.handler.SNSEventHandler
    timeout: 60
    events:
      - sns:
          topicName: AmazonRekognitionTopic1
    