service: simple-todo-sls

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  environment:
    TABLE_NAME: ${self:custom.tableName}
    QUEUE_URL: !Ref todontsQueue
  iamRoleStatements:
    - Effect: Allow
      Action: sqs:sendMessage
      Resource: ${self:custom.queueArn}
    - Effect: Allow
      Action: dynamodb:putItem
      Resource: ${self:custom.tableArn}

custom:
  tableName: ${self:service}-table
  queueName: ${self:service}-queue
  tableArn:
    Fn::GetAtt: [todontsTable, Arn]
  queueArn:
    Fn::GetAtt: [todontsQueue, Arn]

functions:
  post:
    handler: src/post-handler.handler
    events:
      - http:
          method: post
          path: todonts
  process:
    handler: src/process-handler.handler
    events:
      - sqs:
          arn: ${self:custom.queueArn}

resources: 
  Resources:
    todontsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: 'PAY_PER_REQUEST'
    todontsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}