service: lambda-apigateway-s3

provider:
  name: aws
  runtime: java8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
  
package:
  artifact: target/lambda-apigateway-s3-1.0.jar
  
custom:
  stage: ${opt:stage}

functions:
  upload-video:
    handler: com.aws.lambda.handler.FileUploadHandler
    timeout: 30
    events:
      - http:
          path: videos
          method: POST
    
